#把prefix从Ctrl-b改成Ctrl-a

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

#用 | 和 - 分屏

bind | split-window -h
bind - split-window -v

unbind '"'
unbind %

#快速重新加载配置

bind r source-file ~/.tmux.conf

#Alt + 方向键切pane

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

#开启鼠标

set -g mouse on

#禁止自动命名

set-option -g allow-rename off


